// SPDX-License-Identifier: MIT
pragma solidity >=0.8.28 <0.9.0;

import {BaoTest} from "@bao-test/BaoTest.sol";
import {HarborFactoryDeployer} from "@harbor/../script/src/HarborFactoryDeployer.sol";
import {IBaoOwnable} from "@bao/interfaces/IBaoOwnable.sol";
import {IStabilityPool} from "src/interfaces/IStabilityPool.sol";
import {IMultipleRewardAccumulator} from "src/interfaces/IMultipleRewardAccumulator.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IMinter} from "src/interfaces/IMinter.sol";
import {UUPSUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import {PostRebalanceRemediationForStabilityPool_v2} from "src/minter/PostRebalanceRemediationForStabilityPool_v2.sol";
import {IBaoRoles} from "@bao/interfaces/IBaoRoles.sol";
import {console2 as console} from "forge-std/console2.sol";

interface IERC4626 {
    function convertToAssets(uint256 shares) external view returns (uint256);
}

/// @title SPL Remediation Upgrade Test
/// @notice Tests the pause -> remediation -> restore upgrade cycle for the
/// ETH::fxUSD stability pool (leveraged), verifying all holder state is preserved.
/// @dev Holder addresses collected via: script/test/collect-holders
/// @dev Run: forge test --mp script/test/SPLRemediationTest.t.sol -vv
contract SPLRemediationTest is BaoTest, HarborFactoryDeployer {
    address stabilityPoolLeveraged;
    address stabilityPoolCollateral;
    address minter;
    address pegged;
    address leveraged;
    address wrappedCollateral;
    address proxyOwner;
    address existingV2Impl;

    // BaoPauser_v1 deployed on mainnet
    address constant PAUSER = 0xd8785d5C51aaDEb3AD1D015Cd67C8A34dBf58f61;

    // All addresses that interacted with haETH or sailETH.
    // Generated by: script/test/collect-holders
    address[] holders;

    // Per-holder snapshots at current state (just before pause)
    uint256[] assetBalBefore;   // SPL pegged deposit
    uint256[] levBalBefore;     // leveraged token balance
    uint256[] pegBalBefore;     // pegged token balance
    uint256[] claimableBefore;  // claimable leveraged rewards from SPL
    uint256[] claimedBefore;    // already claimed leveraged rewards
    uint256[] spcDepositBefore; // SPC pegged deposit

    // Per-holder balances and value before the first rebalance (the target)
    uint256[] preRebalanceLevBal;   // sailETH held
    uint256[] preRebalanceValue;
    // Per-holder value now (post-bug, pre-remediation) — in ETH
    uint256[] currentValue;

    // Block before the first rebalance
    uint256 constant PRE_REBALANCE_BLOCK = 24687073;
    // Fork before the pause transaction (block 24706805)
    uint256 constant FORK_BLOCK = 24706804;

    function setUp() public {
        string memory rpc = vm.rpcUrl("mainnet");

        // First fork: capture pre-rebalance values (the target)
        vm.createSelectFork(rpc, PRE_REBALANCE_BLOCK);
        _setSaltPrefix("harbor_v1");

        stabilityPoolLeveraged = _predictAddress("ETH", "fxUSD", "stabilityPoolLeveraged");
        stabilityPoolCollateral = _predictAddress("ETH", "fxUSD", "stabilityPoolCollateral");
        minter = _predictAddress("ETH", "fxUSD", "minter");
        pegged = _predictAddress("ETH", "pegged");
        leveraged = _predictAddress("ETH", "fxUSD", "leveraged");
        wrappedCollateral = IMinter(minter).WRAPPED_COLLATERAL_TOKEN();

        _initHolders();
        _capturePreRebalanceValues();

        // Second fork: the actual state just before the pause
        vm.createSelectFork(rpc, FORK_BLOCK);
        // Re-predict addresses (fork changed, labels need re-setting)
        _setSaltPrefix("harbor_v1");
        stabilityPoolLeveraged = _predictAddress("ETH", "fxUSD", "stabilityPoolLeveraged");
        stabilityPoolCollateral = _predictAddress("ETH", "fxUSD", "stabilityPoolCollateral");
        minter = _predictAddress("ETH", "fxUSD", "minter");
        pegged = _predictAddress("ETH", "pegged");
        leveraged = _predictAddress("ETH", "fxUSD", "leveraged");
        proxyOwner = IBaoOwnable(stabilityPoolLeveraged).owner();

        // Read existing v2 implementation from ERC-1967 slot
        existingV2Impl = address(uint160(uint256(vm.load(
            stabilityPoolLeveraged,
            0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc
        ))));
    }

    /// @dev Capture each holder's total value before the first rebalance.
    /// This is the target: remediation should restore everyone to this value.
    function _capturePreRebalanceValues() private {
        uint256 levPrice = IMinter(minter).leveragedTokenPrice();
        pegPrice = IMinter(minter).peggedTokenPrice();

        for (uint256 i = 0; i < holders.length; i++) {
            preRebalanceLevBal.push(IERC20(leveraged).balanceOf(holders[i]));
            preRebalanceValue.push(_holderValueAt(holders[i], levPrice));
        }
    }

    /// @dev All addresses that interacted with haETH or sailETH.
    /// Generated by: script/test/collect-holders
    function _initHolders() private {
        holders.push(0x08453DdD21Cae8f430a07eB8c82e0520882e82c1);
        holders.push(0x13F210c8bAf5f5DBAFf3E917E2e5A49E73BBAF12);
        holders.push(0x1a9152528AEFbcD9E5df4E0770f4F510e7056913);
        holders.push(0x1e085ff3CdD38b1E5F04Ace2345966056F0C85E4);
        holders.push(0x1F985CF7C10A81DE1940da581208D2855D263D72);
        holders.push(0x31632636D664895f1BD9D03f5F7c162A2A6980EB);
        holders.push(0x3dFc49e5112005179Da613BdE5973229082dAc35);
        holders.push(0x3Fdaf8A9af23D27C884e10820130eAB1dB6dDBeD);
        holders.push(0x4382916A88b6EEd40530ef47deD0D402563dDACa);
        holders.push(0x438B29EC7a1770dDbA37D792F1A6e76231Ef8E06);
        holders.push(0x4dAf8ce9D729ca4F121381ec4B22123627C1C004);
        holders.push(0x50b3Bf1B3119afc37A25c841c06C1BDD05Da1Fab);
        holders.push(0x6453E9D859fE2578DfC4aa8D3ec7B3a80574C00f);
        holders.push(0x742fC5146d7Ff18291E3B7499811AD87015Fc7E4);
        holders.push(0x754Ba099408892F500e3675b9816ea1B0dc33CBb);
        holders.push(0x7F14A89F5333A334C0EA3B5AAA7Dc2c8E1C72de6);
        holders.push(0x81253f3Fc43D5e399610beE4D7a235826A7663b8);
        holders.push(0x8335459a89A17Ed8ed128aa98F9AF86802DACF30);
        holders.push(0x8AcF2f327e47FdDD1124a55eb4eFC1DfdAcAA34c);
        holders.push(0x8b7698945dBCedF33F5e8d9E62B1Af8101318575);
        holders.push(0x97C79691407Aea845FaA24C8A905bC3151034ADD);
        holders.push(0x98e917437041f213472C02835cdDC39356086618);
        holders.push(0x9bABfC1A1952a6ed2caC1922BFfE80c0506364a2);
        holders.push(0x9db1D99D1C79A3A2C0123fcd0abB13d9B7c75657);
        holders.push(0x9Dd897df19FfC27d6685E98Accc394f88a73e475);
        holders.push(0xAE7Dbb17bc40D53A6363409c6B1ED88d3cFdc31e);
        holders.push(0xb2810d84dE0A80d0560D8C1FCF1c0589F850592c);
        holders.push(0xb9ab9578a34a05c86124c399735fdE44dEc80E7F);
        holders.push(0xbA26035B9CD76cdA5b767A966b8A3392E476Fc0F);
        holders.push(0xc16A44D0759ec03c677E97eF020a2345d4dC27Fb);
        holders.push(0xC9df4f62474Cf6cdE6c064DB29416a9F4f27EBdC);
        holders.push(0xcadF9F065e96516483afF69fBd8D0b81201199d9);
        holders.push(0xD1AE4d9205F07333916f628850Fc79f1366dC2F8);
        holders.push(0xd6E2F8e57b4aFB51C6fA4cbC012e1cE6aEad989F);
        holders.push(0xDC1330EF8dc913C39bd29F9523418eEEacEf03D6);
        holders.push(0xDD0CDF8D98d9Ad3ADfaa49AaECD444Bfa01d9C9a);
        holders.push(0xdd9c0BB1102D45357bEC81BbdffBb615D64C0ff9);
        holders.push(0xE60849FA39c4D4Ebef88C95cB27583bA2ea26E78);
        holders.push(0xeebF37253066532AFeB3FACB4f2C411703353a83);
        holders.push(0xef5E7606769400DC667DDC520C911D84405e61b7);
        holders.push(0xF7e64540f42094497E2De0F06232992b03942898);
        holders.push(0xf7e9CAaaEEb6cC9657E1Dd490F044114AecC31B2);
    }

    /// @dev Snapshot all holder balances into storage arrays.
    function _snapshotAll() private {
        IStabilityPool spl = IStabilityPool(stabilityPoolLeveraged);
        IMultipleRewardAccumulator acc = IMultipleRewardAccumulator(stabilityPoolLeveraged);
        address liqToken = spl.LIQUIDATION_TOKEN();

        for (uint256 i = 0; i < holders.length; i++) {
            address h = holders[i];
            assetBalBefore.push(spl.assetBalanceOf(h));
            levBalBefore.push(IERC20(leveraged).balanceOf(h));
            pegBalBefore.push(IERC20(pegged).balanceOf(h));
            claimableBefore.push(acc.claimable(h, liqToken));
            claimedBefore.push(acc.claimed(h, liqToken));
            spcDepositBefore.push(IStabilityPool(stabilityPoolCollateral).assetBalanceOf(h));
        }
    }

    /// @dev Verify all holder balances match pre-upgrade snapshot.
    function _verifyAll() private view {
        IStabilityPool spl = IStabilityPool(stabilityPoolLeveraged);
        address liqToken = spl.LIQUIDATION_TOKEN();
        uint256 failures;

        for (uint256 i = 0; i < holders.length; i++) {
            address h = holders[i];

            uint256 assetBal = spl.assetBalanceOf(h);
            uint256 levBal = IERC20(leveraged).balanceOf(h);
            uint256 pegBal = IERC20(pegged).balanceOf(h);
            uint256 claimable = IMultipleRewardAccumulator(stabilityPoolLeveraged).claimable(h, liqToken);
            uint256 spcDeposit = IStabilityPool(stabilityPoolCollateral).assetBalanceOf(h);

            bool anyDiff = assetBal != assetBalBefore[i]
                || levBal != levBalBefore[i]
                || pegBal != pegBalBefore[i]
                || claimable != claimableBefore[i]
                || spcDeposit != spcDepositBefore[i];

            if (anyDiff) {
                console.log("  DIFF %s", h);
                if (assetBal != assetBalBefore[i])
                    console.log("    SPL deposit:  %e -> %e", assetBalBefore[i], assetBal);
                if (levBal != levBalBefore[i])
                    console.log("    sailETH bal:  %e -> %e", levBalBefore[i], levBal);
                if (pegBal != pegBalBefore[i])
                    console.log("    haETH bal:    %e -> %e", pegBalBefore[i], pegBal);
                if (claimable != claimableBefore[i])
                    console.log("    claimable:    %e -> %e", claimableBefore[i], claimable);
                if (spcDeposit != spcDepositBefore[i])
                    console.log("    SPC deposit:  %e -> %e", spcDepositBefore[i], spcDeposit);
                failures++;
            }
        }

        assertEq(failures, 0, "some holders have changed state");
    }

    /// @dev Log holders with non-zero positions.
    function _logHoldings() private view {
        IStabilityPool spl = IStabilityPool(stabilityPoolLeveraged);
        address liqToken = spl.LIQUIDATION_TOKEN();

        for (uint256 i = 0; i < holders.length; i++) {
            address h = holders[i];
            uint256 levBal = IERC20(leveraged).balanceOf(h);
            uint256 pegBal = IERC20(pegged).balanceOf(h);
            uint256 splDep = spl.assetBalanceOf(h);
            uint256 spcDep = IStabilityPool(stabilityPoolCollateral).assetBalanceOf(h);
            uint256 claimable = IMultipleRewardAccumulator(stabilityPoolLeveraged).claimable(h, liqToken);

            if (levBal == 0 && pegBal == 0 && splDep == 0 && spcDep == 0 && claimable == 0) continue;

            console.log("  %s", h);
            if (levBal > 0)    console.log("    sailETH:   %e", levBal);
            if (pegBal > 0)    console.log("    haETH:     %e", pegBal);
            if (splDep > 0)    console.log("    SPL dep:   %e", splDep);
            if (spcDep > 0)    console.log("    SPC dep:   %e", spcDep);
            if (claimable > 0) console.log("    claimable: %e", claimable);
        }
    }

    // Prices captured before and after remediation
    uint256 levPriceBefore;
    uint256 levPriceAfter;
    uint256 pegPrice;

    /// @dev Capture each holder's current value (post-bug, pre-remediation).
    function _captureCurrentValues() private {
        for (uint256 i = 0; i < holders.length; i++) {
            currentValue.push(_holderValueAt(holders[i], levPriceBefore));
        }
    }

    /// @dev Total value for a holder in ETH, including:
    /// - leveraged tokens (held + claimable from SPL) at levPrice
    /// - pegged tokens (held + SPL deposit + SPC deposit) at pegPrice
    /// - collateral rewards (claimable from SPC + held wCol) at wCol price
    function _holderValueAt(address h, uint256 levPrice) private view returns (uint256 value) {
        // Leveraged side
        IMultipleRewardAccumulator splAcc = IMultipleRewardAccumulator(stabilityPoolLeveraged);
        uint256 totalLev = IERC20(leveraged).balanceOf(h) + splAcc.claimable(h, leveraged);

        // Pegged side: wallet + sail stability pool deposit only.
        // SPC deposit and fxSAVE rewards are excluded from all columns because
        // the collateral stability pool side is unaffected by the bug — pegged
        // was correctly exchanged for collateral. Including either side without
        // the other creates a false gain/loss from the conversion.
        uint256 totalPeg = IERC20(pegged).balanceOf(h)
            + IStabilityPool(stabilityPoolLeveraged).assetBalanceOf(h);

        value = totalLev * levPrice / 1 ether
            + totalPeg * pegPrice / 1 ether;
    }

    /// @notice Test the full pause -> remediate -> restore cycle.
    function test_pause_remediate_restore() public {
        console.log("=== PRE-REMEDIATION HOLDINGS ===");
        _logHoldings();

        uint256 totalAssetsBefore = IStabilityPool(stabilityPoolLeveraged).totalAssetSupply();
        uint256 levSupplyBefore = IERC20(leveraged).totalSupply();

        levPriceBefore = IMinter(minter).leveragedTokenPrice();
        pegPrice = IMinter(minter).peggedTokenPrice();

        console.log("");
        console.log("=== POOL TOTALS ===");
        console.log("  totalAssetSupply:  %e", totalAssetsBefore);
        console.log("  SPL lev balance:   %e", IERC20(leveraged).balanceOf(stabilityPoolLeveraged));
        console.log("  lev totalSupply:   %e", levSupplyBefore);
        console.log("  lev price:         %e", levPriceBefore);

        _snapshotAll();

        // Capture "value now" (post-bug, pre-remediation) for each holder
        _captureCurrentValues();

        // ---- Pause -> Remediate -> Restore ----
        _doRemediate();

        levPriceAfter = IMinter(minter).leveragedTokenPrice();
        uint256 levSupplyAfter = IERC20(leveraged).totalSupply();

        console.log("");
        console.log("=== POST-REMEDIATION STATE ===");
        console.log("  lev price before:  %e", levPriceBefore);
        console.log("  lev price after:   %e", levPriceAfter);
        console.log("  lev supply:        %e -> %e", levSupplyBefore, levSupplyAfter);
        console.log("  tokens burned:     %e", levSupplyBefore - levSupplyAfter);

        assertEq(IStabilityPool(stabilityPoolLeveraged).totalAssetSupply(), totalAssetsBefore, "totalAssetSupply changed");
        assertGt(levPriceAfter, levPriceBefore, "lev price should increase");

        // ---- Value analysis ----
        _logTables();
    }

    /// @dev Execute the full pause -> remediate -> restore sequence.
    function _doRemediate() private {
        // Pause
        vm.prank(proxyOwner);
        UUPSUpgradeable(stabilityPoolLeveraged).upgradeToAndCall(PAUSER, "");

        // Grant BURNER_ROLE
        vm.prank(IBaoOwnable(leveraged).owner());
        IBaoRoles(leveraged).grantRoles(stabilityPoolLeveraged, 1 << 1);

        // Remediate
        PostRebalanceRemediationForStabilityPool_v2 impl =
            new PostRebalanceRemediationForStabilityPool_v2(leveraged, proxyOwner);
        vm.prank(proxyOwner);
        UUPSUpgradeable(stabilityPoolLeveraged).upgradeToAndCall(
            address(impl),
            abi.encodeCall(PostRebalanceRemediationForStabilityPool_v2.remediate, ())
        );

        // Restore
        vm.prank(proxyOwner);
        UUPSUpgradeable(stabilityPoolLeveraged).upgradeToAndCall(existingV2Impl, "");
    }

    /// @dev Write combined value + token count CSV.
    function _logTables() private {
        // Build CSV content
        string memory csv = "Address,Value Target ($),Value Now ($),Value Post ($),Recovered ($),vs Target ($),sailETH Pre-Held,sailETH Now-Held,sailETH Claimable,sailETH Excess\n";

        int256 totalRecovered;
        int256 totalVsTarget;

        for (uint256 i = 0; i < holders.length; i++) {
            if (holders[i] == stabilityPoolLeveraged || holders[i] == stabilityPoolCollateral) continue;

            (bool show, int256 rec, int256 vt, string memory row) = _csvRow(i);
            if (!show) continue;
            totalRecovered += rec;
            totalVsTarget += vt;
            csv = string.concat(csv, row, "\n");
        }

        // Add totals row
        csv = string.concat(csv,
            "TOTAL,,,,",
            _signedCsvUsd(totalRecovered), ",",
            _signedCsvUsd(totalVsTarget), ",,,,\n"
        );

        vm.createDir("tmp", true);
        vm.writeFile("tmp/remediation_analysis.csv", csv);
        console.log("  Analysis written to tmp/remediation_analysis.csv");
        console.log(string.concat("  Recovered by remediation: ", _signedCsvUsd(totalRecovered)));
        console.log(string.concat("  vs Target: ", _signedCsvUsd(totalVsTarget), " (includes ETH price movement)"));
    }

    // Temp storage for row data to avoid stack depth issues
    uint256[7] private _row;  // target, now, post, preHeld, nowHeld, claimable, claimed

    function _csvRow(uint256 i) private returns (bool show, int256 recovered, int256 vsTarget, string memory row) {
        IMultipleRewardAccumulator acc = IMultipleRewardAccumulator(stabilityPoolLeveraged);
        _row[0] = preRebalanceValue[i];
        _row[1] = currentValue[i];
        _row[2] = _holderValueAt(holders[i], levPriceAfter);
        _row[3] = preRebalanceLevBal[i];
        _row[4] = IERC20(leveraged).balanceOf(holders[i]);
        _row[5] = acc.claimable(holders[i], leveraged);
        _row[6] = acc.claimed(holders[i], leveraged);

        if (_row[0] == 0 && _row[1] == 0 && _row[2] == 0 && _row[3] == 0 && _row[4] == 0)
            return (false, 0, 0, "");

        show = true;
        recovered = int256(_row[2]) - int256(_row[1]);
        vsTarget = int256(_row[2]) - int256(_row[0]);

        uint256 heldIncrease = _row[4] > _row[3] ? _row[4] - _row[3] : 0;
        uint256 excess = heldIncrease > _row[6] ? heldIncrease : _row[6];

        row = string.concat(
            vm.toString(holders[i]), ",",
            _csvUsd(_row[0]), ",",
            _csvUsd(_row[1]), ",",
            _csvUsd(_row[2]), ","
        );
        row = string.concat(row,
            _signedCsvUsd(recovered), ",",
            _signedCsvUsd(vsTarget), ",",
            _fmtTokens(_row[3]), ",",
            _fmtTokens(_row[4]), ",",
            _fmtTokens(_row[5]), ",",
            excess == 0 ? "" : _fmtTokens(excess)
        );
    }

    /// @dev Format wei as CSV-friendly USD: "1234.56" (no $ sign, for spreadsheet).
    function _csvUsd(uint256 wei_) private pure returns (string memory) {
        uint256 cents = wei_ * ETH_USD / 1e16;
        uint256 whole = cents / 100;
        uint256 frac = cents % 100;
        string memory fracStr = vm.toString(frac);
        if (bytes(fracStr).length < 2) fracStr = string.concat("0", fracStr);
        return string.concat(vm.toString(whole), ".", fracStr);
    }

    function _signedCsvUsd(int256 v) private pure returns (string memory) {
        if (v >= 0) return _csvUsd(uint256(v));
        return string.concat("-", _csvUsd(uint256(-v)));
    }

    /// @dev Left-pad (right-align) a string to width.
    function _pad(string memory s, uint256 width) private pure returns (string memory) {
        bytes memory b = bytes(s);
        if (b.length >= width) return s;
        uint256 padding = width - b.length;
        bytes memory padded = new bytes(width);
        for (uint256 i = 0; i < padding; i++) padded[i] = " ";
        for (uint256 i = 0; i < b.length; i++) padded[padding + i] = b[i];
        return string(padded);
    }

    /// @dev Format token amount as "X.XXXX" with 4 decimal places.
    function _fmtTokens(uint256 amount) private pure returns (string memory) {
        uint256 whole = amount / 1 ether;
        uint256 frac = (amount % 1 ether) / 1e14;
        string memory fracStr = vm.toString(frac);
        while (bytes(fracStr).length < 4) fracStr = string.concat("0", fracStr);
        return string.concat(vm.toString(whole), ".", fracStr);
    }

    function _signedTokens(int256 v) private pure returns (string memory) {
        if (v >= 0) return string.concat("+", _fmtTokens(uint256(v)));
        return string.concat("-", _fmtTokens(uint256(-v)));
    }

    function _shortAddr(address a) private pure returns (string memory) {
        string memory full = vm.toString(a);
        // Return first 6 + last 4 chars: 0x1234...abcd
        bytes memory b = bytes(full);
        bytes memory result = new bytes(13); // "0x1234...abcd"
        for (uint256 i = 0; i < 6; i++) result[i] = b[i];
        result[6] = ".";
        result[7] = ".";
        result[8] = ".";
        for (uint256 i = 0; i < 4; i++) result[9 + i] = b[b.length - 4 + i];
        return string(result);
    }

    function _signedUsd(int256 v) private pure returns (string memory) {
        if (v >= 0) {
            return string.concat("+", _usd(uint256(v)));
        } else {
            return string.concat("-", _usd(uint256(-v)));
        }
    }

    uint256 constant ETH_USD = 2151; // ETH price in USD

    /// @dev Format wei as "$X.YY" (USD via ETH price).
    function _usd(uint256 wei_) private pure returns (string memory) {
        uint256 cents = wei_ * ETH_USD / 1e16; // wei -> cents (1e18 * price / 1e18 * 100)
        uint256 whole = cents / 100;
        uint256 frac = cents % 100;
        string memory fracStr = vm.toString(frac);
        if (bytes(fracStr).length < 2) {
            fracStr = string.concat("0", fracStr);
        }
        return string.concat("$", vm.toString(whole), ".", fracStr);
    }

    function _logTableRow(address h, uint256 valB, uint256 valA, int256 delta) private pure {
        uint256 absDelta = delta > 0 ? uint256(delta) : uint256(-delta);
        console.log(string.concat(
            "| ", vm.toString(h),
            " | ", _usd(valB),
            " | ", _usd(valA),
            " | ", delta < 0 ? "-" : "+", _usd(absDelta),
            " |"
        ));
    }
}
