[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["LeveragedToken_v1", "Minter_v1"]
fs_permissions = [{ access = "read", path = "./"}, { access = "read-write", path = "./results"}]
auto_detect_remappings = false # remappings seem to cause problems


[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
