#!/usr/bin/env bash
#
# Run predict on all harbor_v1 SP deployments
#

set -euo pipefail

cd "$(dirname "$0")/.."

for f in \
  harbor_v1::BTC::fxUSD::minter \
  harbor_v1::BTC::stETH::minter \
  harbor_v1::ETH::fxUSD::minter \
  harbor_v1::EUR::fxUSD::minter \
  harbor_v1::GOLD::fxUSD::minter; do
  echo "=== $f ==="
  ./script/predict "$f"
  echo
done
